# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'apptest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for apptest
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

end

